"""
Comprehensive Foursquare subcategory → 7-class taxonomy mapping.

Covers all unique venue_category_name values found in:
  - Foursquare TIST2015 (NYC + Tokyo): ~251 unique subcategory names
  - Massive-STEPS (all 15 cities):     ~617 unique subcategory names

The 7-class taxonomy (matches CATEGORIES_MAP in src/configs/globals.py):
  Food, Nightlife, Entertainment, Outdoors, Shopping, Travel, Community

Names not in this dict are dropped during ETL (return None via map_category).
"""

# Comprehensive mapping: Foursquare (sub)category → 7-class taxonomy
SUBCATEGORY_TO_SUPER: dict[str, str] = {
    # ── FOOD ─────────────────────────────────────────────────────────────────
    # Restaurants by cuisine
    "Afghan Restaurant": "Food",
    "African Restaurant": "Food",
    "American Restaurant": "Food",
    "Arepa Restaurant": "Food",
    "Argentinian Restaurant": "Food",
    "Asian Restaurant": "Food",
    "Australian Restaurant": "Food",
    "Austrian Restaurant": "Food",
    "BBQ Joint": "Food",
    "Belgian Restaurant": "Food",
    "Bistro": "Food",
    "Brazilian Restaurant": "Food",
    "Burmese Restaurant": "Food",
    "Cajun / Creole Restaurant": "Food",
    "Cambodian Restaurant": "Food",
    "Cantonese Restaurant": "Food",
    "Caribbean Restaurant": "Food",
    "Chinese Restaurant": "Food",
    "Churrascaria": "Food",
    "Colombian Restaurant": "Food",
    "Comfort Food Restaurant": "Food",
    "Cuban Restaurant": "Food",
    "Czech Restaurant": "Food",
    "Dim Sum Restaurant": "Food",
    "Donburi Restaurant": "Food",
    "Dumpling Restaurant": "Food",
    "Eastern European Restaurant": "Food",
    "Empanada Restaurant": "Food",
    "English Restaurant": "Food",
    "Ethiopian Restaurant": "Food",
    "Falafel Restaurant": "Food",
    "Fast Food Restaurant": "Food",
    "Filipino Restaurant": "Food",
    "Fish & Chips Shop": "Food",
    "French Restaurant": "Food",
    "Fried Chicken Joint": "Food",
    "German Restaurant": "Food",
    "Gluten-free Restaurant": "Food",
    "Greek Restaurant": "Food",
    "Grilled Meat Restaurant": "Food",
    "Halal Restaurant": "Food",
    "Hawaiian Restaurant": "Food",
    "Himalayan Restaurant": "Food",
    "Hotpot Restaurant": "Food",
    "Hunan Restaurant": "Food",
    "Indian Chinese Restaurant": "Food",
    "Indian Restaurant": "Food",
    "Indonesian Restaurant": "Food",
    "Israeli Restaurant": "Food",
    "Italian Restaurant": "Food",
    "Japanese Curry Restaurant": "Food",
    "Japanese Restaurant": "Food",
    "Jewish Restaurant": "Food",
    "Korean Restaurant": "Food",
    "Kosher Restaurant": "Food",
    "Latin American Restaurant": "Food",
    "Lebanese Restaurant": "Food",
    "Mac & Cheese Joint": "Food",
    "Malay Restaurant": "Food",
    "Malaysian Restaurant": "Food",
    "Mediterranean Restaurant": "Food",
    "Mexican Restaurant": "Food",
    "Middle Eastern Restaurant": "Food",
    "Modern European Restaurant": "Food",
    "Molecular Gastronomy Restaurant": "Food",
    "Mongolian Restaurant": "Food",
    "Moroccan Restaurant": "Food",
    "New American Restaurant": "Food",
    "North Indian Restaurant": "Food",
    "Okonomiyaki Restaurant": "Food",
    "Paella Restaurant": "Food",
    "Pakistani Restaurant": "Food",
    "Peking Duck Restaurant": "Food",
    "Persian Restaurant": "Food",
    "Peruvian Restaurant": "Food",
    "Polish Restaurant": "Food",
    "Portuguese Restaurant": "Food",
    "Russian Restaurant": "Food",
    "Scandinavian Restaurant": "Food",
    "Seafood Restaurant": "Food",
    "Shabu-Shabu Restaurant": "Food",
    "Shanghai Restaurant": "Food",
    "Soba Restaurant": "Food",
    "South American Restaurant": "Food",
    "South Indian Restaurant": "Food",
    "Southern / Soul Food Restaurant": "Food",
    "Spanish Restaurant": "Food",
    "Sri Lankan Restaurant": "Food",
    "Swiss Restaurant": "Food",
    "Szechuan Restaurant": "Food",
    "Taiwanese Restaurant": "Food",
    "Tapas Restaurant": "Food",
    "Tempura Restaurant": "Food",
    "Tex-Mex Restaurant": "Food",
    "Thai Restaurant": "Food",
    "Theme Restaurant": "Food",
    "Tibetan Restaurant": "Food",
    "Tonkatsu Restaurant": "Food",
    "Turkish Restaurant": "Food",
    "Udon Restaurant": "Food",
    "Ukrainian Restaurant": "Food",
    "Varenyky restaurant": "Food",
    "Vegetarian / Vegan Restaurant": "Food",
    "Venezuelan Restaurant": "Food",
    "Vietnamese Restaurant": "Food",
    "Yakitori Restaurant": "Food",
    "Yoshoku Restaurant": "Food",
    # Casual eateries and food concepts
    "Bagel Shop": "Food",
    "Bakery": "Food",
    "Breakfast Spot": "Food",
    "Bubble Tea Shop": "Food",
    "Buffet": "Food",
    "Burger Joint": "Food",
    "Burrito Place": "Food",
    "Candy Store": "Food",
    "Chocolate Shop": "Food",
    "Coffee Shop": "Food",
    "Creperie": "Food",
    "Cupcake Shop": "Food",
    "Deli / Bodega": "Food",
    "Dessert Shop": "Food",
    "Diner": "Food",
    "Donut Shop": "Food",
    "Food Court": "Food",
    "Food Stand": "Food",
    "Food Truck": "Food",
    "Frozen Yogurt Shop": "Food",
    "Gastropub": "Food",
    "Hot Dog Joint": "Food",
    "Ice Cream Shop": "Food",
    "Internet Cafe": "Food",
    "Juice Bar": "Food",
    "Noodle House": "Food",
    "Pie Shop": "Food",
    "Pizza Place": "Food",
    "Poke Place": "Food",
    "Poutine Place": "Food",
    "Ramen Restaurant": "Food",
    "Ramen /  Noodle House": "Food",
    "Restaurant": "Food",
    "Salad Place": "Food",
    "Sandwich Place": "Food",
    "Smoothie Shop": "Food",
    "Snack Place": "Food",
    "Soup Place": "Food",
    "Souvlaki Shop": "Food",
    "Steakhouse": "Food",
    "Street Food Gathering": "Food",
    "Sushi Restaurant": "Food",
    "Taco Place": "Food",
    "Tea Room": "Food",
    "Wagashi Place": "Food",
    "Wings Joint": "Food",
    # Cafés (with proper encoding)
    "Café": "Food",
    "Café (Caf\u00e9)": "Food",
    "Pet Café": "Food",
    "Pet Caf\u00e9": "Food",
    # Cafeterias (eat-in institutional food)
    "Cafeteria": "Food",
    "College Cafeteria": "Food",
    "Corporate Cafeteria": "Food",
    "Corporate Coffee Shop": "Food",
    "Airport Food Court": "Food",
    # Food (FSQ top-level)
    "Food": "Food",

    # ── NIGHTLIFE ─────────────────────────────────────────────────────────────
    "Apres Ski Bar": "Nightlife",
    "Bar": "Nightlife",
    "Beach Bar": "Nightlife",
    "Beer Bar": "Nightlife",
    "Beer Garden": "Nightlife",
    "Brewery": "Nightlife",
    "Cocktail Bar": "Nightlife",
    "Distillery": "Nightlife",
    "Dive Bar": "Nightlife",
    "Gay Bar": "Nightlife",
    "Hookah Bar": "Nightlife",
    "Hotel Bar": "Nightlife",
    "Irish Pub": "Nightlife",
    "Jazz Club": "Nightlife",
    "Karaoke Bar": "Nightlife",
    "Karaoke Box": "Nightlife",
    "Lounge": "Nightlife",
    "Nightclub": "Nightlife",
    "Other Nightlife": "Nightlife",
    "Piano Bar": "Nightlife",
    "Pool Hall": "Nightlife",
    "Pub": "Nightlife",
    "Rock Club": "Nightlife",
    "Sake Bar": "Nightlife",
    "Salsa Club": "Nightlife",
    "Speakeasy": "Nightlife",
    "Sports Bar": "Nightlife",
    "Strip Club": "Nightlife",
    "Tiki Bar": "Nightlife",
    "Whisky Bar": "Nightlife",
    "Wine Bar": "Nightlife",
    # Nightlife Spot (FSQ top-level)
    "Nightlife Spot": "Nightlife",

    # ── ENTERTAINMENT ─────────────────────────────────────────────────────────
    # Museums and galleries
    "Aquarium": "Entertainment",
    "Art Gallery": "Entertainment",
    "Art Museum": "Entertainment",
    "Erotic Museum": "Entertainment",
    "History Museum": "Entertainment",
    "Museum": "Entertainment",
    "Planetarium": "Entertainment",
    "Science Museum": "Entertainment",
    # Performing arts
    "Amphitheater": "Entertainment",
    "Auditorium": "Entertainment",
    "Comedy Club": "Entertainment",
    "Concert Hall": "Entertainment",
    "Indie Theater": "Entertainment",
    "Music Festival": "Entertainment",
    "Music Venue": "Entertainment",
    "Opera House": "Entertainment",
    "Performing Arts Venue": "Entertainment",
    "Theater": "Entertainment",
    # Games and recreation
    "Arcade": "Entertainment",
    "Bowling Alley": "Entertainment",
    "Casino": "Entertainment",
    "Gaming Cafe": "Entertainment",
    "Gun Range": "Entertainment",
    "Indoor Play Area": "Entertainment",
    "Mini Golf": "Entertainment",
    "Movie Theater": "Entertainment",
    "Multiplex": "Entertainment",
    "Indie Movie Theater": "Entertainment",
    "Pachinko Parlor": "Entertainment",
    "Roller Rink": "Entertainment",
    "Water Park": "Entertainment",
    # Stadiums and arenas
    "Baseball Stadium": "Entertainment",
    "Basketball Stadium": "Entertainment",
    "College Stadium": "Entertainment",
    "College Theater": "Entertainment",
    "Football Stadium": "Entertainment",
    "Hockey Arena": "Entertainment",
    "Soccer Stadium": "Entertainment",
    "Stadium": "Entertainment",
    "Tennis Stadium": "Entertainment",
    "Track Stadium": "Entertainment",
    # Events and cultural
    "Convention": "Entertainment",
    "Convention Center": "Entertainment",
    "Cultural Center": "Entertainment",
    "Event Space": "Entertainment",
    "Exhibit": "Entertainment",
    "Fair": "Entertainment",
    "Festival": "Entertainment",
    "Film Studio": "Entertainment",
    "Historic Site": "Entertainment",
    "Other Event": "Entertainment",
    "Outdoor Event Space": "Entertainment",
    "Outdoor Sculpture": "Entertainment",
    "Public Art": "Entertainment",
    "Castle": "Entertainment",
    "Racetrack": "Entertainment",
    "Sculpture Garden": "Entertainment",
    "Street Art": "Entertainment",
    "Street Fair": "Entertainment",
    "Theme Park": "Entertainment",
    "Theme Park Ride / Attraction": "Entertainment",
    "Tourist Information Center": "Entertainment",
    "Vineyard": "Entertainment",
    "Winery": "Entertainment",
    "Zoo": "Entertainment",
    "Zoo Exhibit": "Entertainment",
    # Arts & Entertainment (FSQ top-level)
    "Arts & Entertainment": "Entertainment",
    # Fallback general
    "General Entertainment": "Entertainment",
    "Athletic & Sport": "Entertainment",
    "Athletics & Sport": "Entertainment",

    # ── OUTDOORS ──────────────────────────────────────────────────────────────
    # Natural areas
    "Beach": "Outdoors",
    "Botanical Garden": "Outdoors",
    "Bridge": "Outdoors",
    "Campground": "Outdoors",
    "Cemetery": "Outdoors",
    "Dog Run": "Outdoors",
    "Farm": "Outdoors",
    "Field": "Outdoors",
    "Fishing Spot": "Outdoors",
    "Garden": "Outdoors",
    "Harbor / Marina": "Outdoors",
    "Hot Spring": "Outdoors",
    "Island": "Outdoors",
    "Lake": "Outdoors",
    "Lighthouse": "Outdoors",
    "Mountain": "Outdoors",
    "Other Great Outdoors": "Outdoors",
    "Park": "Outdoors",
    "Pedestrian Plaza": "Outdoors",
    "Pier": "Outdoors",
    "Plaza": "Outdoors",
    "Reservoir": "Outdoors",
    "River": "Outdoors",
    "Road": "Outdoors",
    "Roof Deck": "Outdoors",
    "Scenic Lookout": "Outdoors",
    "Stables": "Outdoors",
    "Surf Spot": "Outdoors",
    "Trail": "Outdoors",
    "Tree": "Outdoors",
    "Tunnel": "Outdoors",
    "Volcano": "Outdoors",
    "Waterfall": "Outdoors",
    "Waterfront": "Outdoors",
    # Sports fields and courts
    "Baseball Field": "Outdoors",
    "Basketball Court": "Outdoors",
    "College Baseball Diamond": "Outdoors",
    "College Basketball Court": "Outdoors",
    "College Football Field": "Outdoors",
    "College Soccer Field": "Outdoors",
    "College Track": "Outdoors",
    "Golf Course": "Outdoors",
    "Golf Driving Range": "Outdoors",
    "Hockey Field": "Outdoors",
    "Skate Park": "Outdoors",
    "Skating Rink": "Outdoors",
    "Soccer Field": "Outdoors",
    "Tennis Court": "Outdoors",
    "Track": "Outdoors",
    "Volleyball Court": "Outdoors",
    # Skiing
    "Ski Area": "Outdoors",
    "Ski Chairlift": "Outdoors",
    "Ski Chalet": "Outdoors",
    "Ski Lodge": "Outdoors",
    "Ski Trail": "Outdoors",
    # Fitness and gyms
    "Bike Rental / Bike Share": "Outdoors",
    "Boxing Gym": "Outdoors",
    "Climbing Gym": "Outdoors",
    "Cycle Studio": "Outdoors",
    "Gym": "Outdoors",
    "Gym / Fitness Center": "Outdoors",
    "Gym Pool": "Outdoors",
    "Gymnastics Gym": "Outdoors",
    "College Gym": "Outdoors",
    "College Rec Center": "Outdoors",
    "Martial Arts Dojo": "Outdoors",
    "Pilates Studio": "Outdoors",
    "Pool": "Outdoors",
    "Playground": "Outdoors",
    "Recreation Center": "Outdoors",
    "Sports Club": "Outdoors",
    "Yoga Studio": "Outdoors",
    # Outdoors & Recreation (FSQ top-level)
    "Outdoors & Recreation": "Outdoors",

    # ── SHOPPING ──────────────────────────────────────────────────────────────
    # General retail
    "Accessories Store": "Shopping",
    "Adult Boutique": "Shopping",
    "Antique Shop": "Shopping",
    "Arts & Crafts Store": "Shopping",
    "Auto Dealership": "Shopping",
    "Auto Garage": "Shopping",
    "Auto Workshop": "Shopping",
    "Automotive Shop": "Shopping",
    "Baby Store": "Shopping",
    "Beer Store": "Shopping",
    "Big Box Store": "Shopping",
    "Bike Shop": "Shopping",
    "Board Shop": "Shopping",
    "Bookstore": "Shopping",
    "Boutique": "Shopping",
    "Bridal Shop": "Shopping",
    "Camera Store": "Shopping",
    "Car Dealership": "Shopping",
    "Car Wash": "Shopping",
    "Christmas Market": "Shopping",
    "Clothing Store": "Shopping",
    "College Bookstore": "Shopping",
    "Comic Shop": "Shopping",
    "Convenience Store": "Shopping",
    "Cosmetics Shop": "Shopping",
    "Costume Shop": "Shopping",
    "Department Store": "Shopping",
    "Discount Store": "Shopping",
    "Drugstore": "Shopping",
    "Drugstore / Pharmacy": "Shopping",
    "Dry Cleaner": "Shopping",
    "Electronics Store": "Shopping",
    "Fabric Shop": "Shopping",
    "Farmers Market": "Shopping",
    "Fish Market": "Shopping",
    "Flea Market": "Shopping",
    "Flower Shop": "Shopping",
    "Food & Drink Shop": "Shopping",
    "Fruit & Vegetable Store": "Shopping",
    "Furniture / Home Store": "Shopping",
    "Garden Center": "Shopping",
    "Gas Station": "Shopping",
    "Gas Station / Garage": "Shopping",
    "Gift Shop": "Shopping",
    "Gourmet Shop": "Shopping",
    "Grocery Store": "Shopping",
    "Hardware Store": "Shopping",
    "Health Food Store": "Shopping",
    "Herbs & Spices Store": "Shopping",
    "Hobby Shop": "Shopping",
    "Jewelry Store": "Shopping",
    "Kids Store": "Shopping",
    "Kitchen Supply Store": "Shopping",
    "Leather Goods Store": "Shopping",
    "Lingerie Store": "Shopping",
    "Liquor Store": "Shopping",
    "Mall": "Shopping",
    "Marijuana Dispensary": "Shopping",
    "Market": "Shopping",
    "Mattress Store": "Shopping",
    "Men's Store": "Shopping",
    "Miscellaneous Shop": "Shopping",
    "Mobile Phone Shop": "Shopping",
    "Motorcycle Shop": "Shopping",
    "Motorsports Shop": "Shopping",
    "Music Store": "Shopping",
    "Night Market": "Shopping",
    "Newsstand": "Shopping",
    "Optical Shop": "Shopping",
    "Organic Grocery": "Shopping",
    "Outdoor Supply Store": "Shopping",
    "Paper / Office Supplies Store": "Shopping",
    "Perfume Shop": "Shopping",
    "Pet Store": "Shopping",
    "Photography Lab": "Shopping",
    "Pop-Up Shop": "Shopping",
    "Print Shop": "Shopping",
    "Record Shop": "Shopping",
    "Rental Service": "Shopping",
    "Shoe Repair": "Shopping",
    "Shoe Store": "Shopping",
    "Shipping Store": "Shopping",
    "Shopping Mall": "Shopping",
    "Shopping Plaza": "Shopping",
    "Smoke Shop": "Shopping",
    "Souvenir Shop": "Shopping",
    "Sporting Goods Shop": "Shopping",
    "Stoop Sale": "Shopping",
    "Supermarket": "Shopping",
    "Supplement Shop": "Shopping",
    "Tailor Shop": "Shopping",
    "Tanning Salon": "Shopping",
    "Tattoo Parlor": "Shopping",
    "Thrift / Vintage Store": "Shopping",
    "Toy / Game Store": "Shopping",
    "Vape Store": "Shopping",
    "Video Game Store": "Shopping",
    "Video Store": "Shopping",
    "Warehouse Store": "Shopping",
    "Watch Shop": "Shopping",
    "Wine Shop": "Shopping",
    "Women's Store": "Shopping",
    # Personal services
    "Nail Salon": "Shopping",
    "Salon / Barbershop": "Shopping",
    "ATM": "Shopping",
    "Bank": "Shopping",
    "Laundry Service": "Shopping",
    "Laundromat": "Shopping",
    # Shop & Service (FSQ top-level)
    "Shop & Service": "Shopping",

    # ── TRAVEL ────────────────────────────────────────────────────────────────
    # Airports
    "Airport": "Travel",
    "Airport Gate": "Travel",
    "Airport Lounge": "Travel",
    "Airport Service": "Travel",
    "Airport Terminal": "Travel",
    "Airport Tram": "Travel",
    "Baggage Claim": "Travel",
    "Heliport": "Travel",
    # Ground transport
    "Boat or Ferry": "Travel",
    "Border Crossing": "Travel",
    "Bus Line": "Travel",
    "Bus Station": "Travel",
    "Bus Stop": "Travel",
    "Cable Car": "Travel",
    "Cruise": "Travel",
    "Ferry": "Travel",
    "Light Rail": "Travel",
    "Light Rail Station": "Travel",
    "Metro Station": "Travel",
    "Parking": "Travel",
    "Plane": "Travel",
    "Platform": "Travel",
    "Port": "Travel",
    "Rental Car Location": "Travel",
    "Rest Area": "Travel",
    "Subway": "Travel",
    "Taxi": "Travel",
    "Toll Booth": "Travel",
    "Toll Plaza": "Travel",
    "Train": "Travel",
    "Train Station": "Travel",
    "Tram Station": "Travel",
    "Transportation Service": "Travel",
    # Accommodation
    "Bed & Breakfast": "Travel",
    "Hostel": "Travel",
    "Hotel": "Travel",
    "Hotel Pool": "Travel",
    "Motel": "Travel",
    "Resort": "Travel",
    # Travel services
    "General Travel": "Travel",
    "Travel Agency": "Travel",
    "Travel Lounge": "Travel",
    # Travel & Transport (FSQ top-level)
    "Travel & Transport": "Travel",

    # ── COMMUNITY ─────────────────────────────────────────────────────────────
    # Residences
    "Assisted Living": "Community",
    "Fraternity House": "Community",
    "Home (private)": "Community",
    "Housing Development": "Community",
    "Neighborhood": "Community",
    "Residential Building (Apartment / Condo)": "Community",
    "Sorority House": "Community",
    "Trailer Park": "Community",
    # Education
    "College & University": "Community",
    "College Academic Building": "Community",
    "College Administrative Building": "Community",
    "College Arts Building": "Community",
    "College Auditorium": "Community",
    "College Communications Building": "Community",
    "College Engineering Building": "Community",
    "College Lab": "Community",
    "College Library": "Community",
    "College Math Building": "Community",
    "College Quad": "Community",
    "College Residence Hall": "Community",
    "College Science Building": "Community",
    "College Technology Building": "Community",
    "Community College": "Community",
    "Cooking School": "Community",
    "Dance Studio": "Community",
    "Driving School": "Community",
    "Elementary School": "Community",
    "General College & University": "Community",
    "High School": "Community",
    "Language School": "Community",
    "Law School": "Community",
    "Library": "Community",
    "Medical School": "Community",
    "Middle School": "Community",
    "Music School": "Community",
    "Nursery School": "Community",
    "Private School": "Community",
    "School": "Community",
    "Student Center": "Community",
    "Trade School": "Community",
    "University": "Community",
    # Healthcare and wellness
    "Acupuncturist": "Community",
    "Animal Shelter": "Community",
    "Chiropractor": "Community",
    "Dentist's Office": "Community",
    "Doctor's Office": "Community",
    "Emergency Room": "Community",
    "Eye Doctor": "Community",
    "Funeral Home": "Community",
    "Health & Beauty Service": "Community",
    "Hospital": "Community",
    "Massage Studio": "Community",
    "Medical Center": "Community",
    "Medical Lab": "Community",
    "Mental Health Office": "Community",
    "Physical Therapist": "Community",
    "Pharmacy": "Shopping",
    "Spa": "Community",
    "Spa / Massage": "Community",
    "Veterinarian": "Community",
    "Weight Loss Center": "Community",
    # Government and civic
    "Campaign Office": "Community",
    "Capitol Building": "Community",
    "City": "Community",
    "City Hall": "Community",
    "County": "Community",
    "Courthouse": "Community",
    "Embassy / Consulate": "Community",
    "Fire Station": "Community",
    "Government Building": "Community",
    "Military Base": "Community",
    "Police Station": "Community",
    "Post Office": "Community",
    "Prison": "Community",
    "Public Bathroom": "Community",
    "Voting Booth": "Community",
    # Religious
    "Buddhist Temple": "Community",
    "Church": "Community",
    "Mosque": "Community",
    "Shrine": "Community",
    "Spiritual Center": "Community",
    "Synagogue": "Community",
    "Temple": "Community",
    # Office and business
    "Advertising Agency": "Community",
    "Art Studio": "Community",
    "Building": "Community",
    "Business Center": "Community",
    "Business Service": "Community",
    "Club House": "Community",
    "Community Center": "Community",
    "Conference Room": "Community",
    "Corporate Amenity": "Community",
    "Coworking Space": "Community",
    "Credit Union": "Community",
    "Currency Exchange": "Community",
    "Design Studio": "Community",
    "Distribution Center": "Community",
    "Factory": "Community",
    "Financial or Legal Service": "Community",
    "Home Service": "Community",
    "Insurance Office": "Community",
    "Intersection": "Community",
    "Laboratory": "Community",
    "Lawyer": "Community",
    "Locksmith": "Community",
    "Meeting Room": "Community",
    "Moving Target": "Community",
    "Non-Profit": "Community",
    "Office": "Community",
    "Other Repair Shop": "Community",
    "Pet Service": "Community",
    "Photography Studio": "Community",
    "Radio Station": "Community",
    "Real Estate Office": "Community",
    "Recording Studio": "Community",
    "Recruiting Agency": "Community",
    "Recycling Facility": "Community",
    "Social Club": "Community",
    "Storage Facility": "Community",
    "Tech Startup": "Community",
    "TV Station": "Community",
    "Warehouse": "Community",
    "Wedding Hall": "Community",
    # Professional & Other Places (FSQ top-level)
    "Professional & Other Places": "Community",
    # Residence (FSQ top-level)
    "Residence": "Community",
}


def map_category(venue_category_name: str) -> str | None:
    """Return the 7-class super-category for a raw Foursquare category name.

    Parameters
    ----------
    venue_category_name:
        Raw string from the dataset's venue_category_name (or venue_category) column.

    Returns
    -------
    One of {Food, Nightlife, Entertainment, Outdoors, Shopping, Travel, Community},
    or None if the name is unknown / should be dropped.
    """
    if not venue_category_name:
        return None
    name = venue_category_name.strip()
    return SUBCATEGORY_TO_SUPER.get(name)
