"""Seed-sweep for Time2Vec: baseline_current vs feat_space across N seeds.

After the 1-seed ablation in scripts/run_time2vec_ablation.py showed
feat_space > baseline (+1.04pp) with std (±1.62) > gain, we need a wider
seed sweep to tell if the effect is real or noise.

This script reruns the same Alabama 2-fold × 25-epoch MTLnet next-task
experiment for each (variant, seed) combination, varying only the Time2Vec
training seed. The MTLnet fold split + training seed stay fixed (default 42),
so the SAME train/val split is used across all runs — this isolates the
embedding effect from fold-split variance.

Output: plans/time2vec_seedsweep_results.md with a seeds × variants grid
and a mean ± std summary for each variant.

Usage:
    python scripts/run_time2vec_seedsweep.py --seeds 42,43,44,45
"""
from __future__ import annotations

import argparse
import json
import statistics
import sys
from argparse import Namespace
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))  # so we can import scripts.*
sys.path.insert(0, str(PROJECT_ROOT / "src"))
sys.path.insert(0, str(PROJECT_ROOT / "research"))

from configs.globals import DEVICE
from configs.model import InputsConfig
from configs.paths import EmbeddingEngine, IoPaths
from embeddings.time2vec.time2vec import create_embedding
from scripts.run_time2vec_ablation import (
    STATE, EMB_PATH, RESULTS_BASE,
    regenerate_inputs, train_mtlnet,
)


VARIANTS: dict[str, dict] = {
    "baseline_current": {},
    "feat_space": {"sampling_mode": "feat_space"},
}


def _t2v_config(seed: int, embed_epochs: int, overrides: dict) -> Namespace:
    cfg = Namespace(
        dim=InputsConfig.EMBEDDING_DIM,
        out_features=64,
        activation="sin",
        lr=1e-3,
        epoch=embed_epochs,
        batch_size=2048,
        r_pos_hours=1.0,
        r_neg_hours=24.0,
        max_pairs=2_000_000,
        k_neg_per_i=5,
        max_pos_per_i=20,
        seed=seed,
        tau=0.3,
        device=DEVICE,
        compile=False,
        sampling_mode="absolute_time",
        r_pos_feat=0.03,
        r_neg_feat=0.30,
        no_train=False,
    )
    for k, v in overrides.items():
        setattr(cfg, k, v)
    return cfg


def parse_live_f1() -> tuple[float, float, list[float]]:
    """Parse macro F1 from the latest next_* run in results/time2vec/alabama/
    (the live, pre-archive path). Returns (mean, std, per_fold).
    """
    base = RESULTS_BASE / STATE
    run_dirs = sorted(base.glob("next_*"))
    if not run_dirs:
        raise FileNotFoundError(f"No next_* dir under {base}")
    latest = run_dirs[-1]
    report_files = sorted((latest / "folds").glob("fold*_next_report.json"))
    f1s: list[float] = []
    for f in report_files:
        with f.open() as fh:
            data = json.load(fh)
        f1s.append(float(data["macro avg"]["f1-score"]))
    mean = statistics.mean(f1s)
    std = statistics.stdev(f1s) if len(f1s) > 1 else 0.0
    return mean, std, f1s


def write_results_md(
    grid: dict[str, dict[int, dict]],
    seeds: list[int],
    embed_epochs: int,
    epochs: int,
    folds: int,
) -> Path:
    out = PROJECT_ROOT / "plans" / "time2vec_seedsweep_results.md"
    lines = [
        "# Time2Vec seed sweep — baseline vs feat_space",
        "",
        f"Generated by `scripts/run_time2vec_seedsweep.py` on Alabama next-task, "
        f"{folds} folds × {epochs} epochs, {embed_epochs} embed epochs. "
        f"Only the Time2Vec training seed varies; MTLnet fold split + training "
        f"seed are fixed.",
        "",
        "F1 values are macro avg in percent, averaged over 2 folds per cell.",
        "",
        "## Per-seed F1",
        "",
        "| Variant \\ Seed | " + " | ".join(str(s) for s in seeds) + " | **Mean ± Std (over seeds)** |",
        "|---|" + "---:|" * len(seeds) + "---:|",
    ]
    for variant in VARIANTS:
        row_cells = []
        per_seed_means = []
        for s in seeds:
            cell = grid[variant].get(s)
            if cell is None:
                row_cells.append("—")
            else:
                row_cells.append(f"{cell['f1_mean'] * 100:.2f}")
                per_seed_means.append(cell["f1_mean"])
        if len(per_seed_means) >= 2:
            m = statistics.mean(per_seed_means)
            sd = statistics.stdev(per_seed_means)
            summary = f"**{m * 100:.2f} ± {sd * 100:.2f}**"
        elif per_seed_means:
            summary = f"**{per_seed_means[0] * 100:.2f}**"
        else:
            summary = "—"
        lines.append(f"| `{variant}` | " + " | ".join(row_cells) + f" | {summary} |")

    # Delta analysis
    lines += ["", "## Delta analysis (feat_space − baseline_current)", ""]
    deltas = []
    for s in seeds:
        b = grid["baseline_current"].get(s)
        f = grid["feat_space"].get(s)
        if b and f:
            deltas.append((s, (f["f1_mean"] - b["f1_mean"]) * 100))
    if deltas:
        lines.append("| Seed | Δ F1 (pp) |")
        lines.append("|---:|---:|")
        for s, d in deltas:
            lines.append(f"| {s} | {d:+.2f} |")
        d_vals = [d for _, d in deltas]
        d_mean = statistics.mean(d_vals)
        d_std = statistics.stdev(d_vals) if len(d_vals) > 1 else 0.0
        lines.append(f"| **mean ± std** | **{d_mean:+.2f} ± {d_std:.2f}** |")

    out.write_text("\n".join(lines) + "\n")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seeds", type=str, default="42,43,44,45",
                        help="Comma-separated list of Time2Vec training seeds")
    parser.add_argument("--epochs", type=int, default=25,
                        help="MTLnet next-task epochs per fold")
    parser.add_argument("--folds", type=int, default=2, help="MTLnet CV folds")
    parser.add_argument("--embed_epochs", type=int, default=100,
                        help="Time2Vec training epochs")
    args = parser.parse_args()

    seeds = [int(s) for s in args.seeds.split(",")]
    print(f"Running sweep: {len(seeds)} seeds × {len(VARIANTS)} variants "
          f"= {len(seeds) * len(VARIANTS)} runs")

    grid: dict[str, dict[int, dict]] = {v: {} for v in VARIANTS}

    for seed in seeds:
        for variant, overrides in VARIANTS.items():
            print(f"\n{'='*72}\n  seed={seed}  variant={variant}\n{'='*72}")

            # 1. Build embedding with this seed
            cfg = _t2v_config(seed, args.embed_epochs, overrides)
            create_embedding(state=STATE, args=cfg)
            # create_embedding wrote to EMB_PATH directly — nothing to copy

            # 2. Regenerate next-task input from the new embedding
            regenerate_inputs()

            # 3. Train MTLnet (subprocess → scripts/train.py)
            train_mtlnet(epochs=args.epochs, folds=args.folds)

            # 4. Parse live F1 before the next run overwrites
            mean, std, f1s = parse_live_f1()
            grid[variant][seed] = {"f1_mean": mean, "f1_std": std, "f1s": f1s}
            print(f"  → seed={seed} {variant}: F1 = {mean * 100:.2f} ± {std * 100:.2f}")

    out = write_results_md(grid, seeds, args.embed_epochs, args.epochs, args.folds)
    print(f"\n{'='*72}\n  Wrote {out}\n{'='*72}")
    for variant in VARIANTS:
        per_seed_means = [grid[variant][s]["f1_mean"] for s in seeds if s in grid[variant]]
        if len(per_seed_means) >= 2:
            m = statistics.mean(per_seed_means)
            sd = statistics.stdev(per_seed_means)
            print(f"  {variant:20s}  F1 = {m * 100:.2f} ± {sd * 100:.2f}  "
                  f"(seeds: {[f'{v*100:.2f}' for v in per_seed_means]})")


if __name__ == "__main__":
    main()
