#!/usr/bin/env python3
"""Regression fixtures for check_trapped_prose.py — every historical case, verified in the repo.

The detector's job is to catch body prose accidentally left inside a LaTeX comment. It has been
wrong four separate times, each time because it was tuned on the cases in front of it, so its
validation cannot live in a /tmp scratch tree that gets swept (that happened, and it silently
turned "rebuild and check" into "check a stale PDF").

Each fixture below is a MINIMAL reproduction of a real defect that shipped in this document, taken
from the commit where it was found. Run:  python3 src_utils/test_trapped_prose.py

The fixtures do not need a LaTeX build: the detector's render test asks whether text appears in the
rendered PDF, so a fixture supplies a stub "rendered text" that deliberately omits the trapped
words, which is exactly what the real PDF did.
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("ctp", HERE / "check_trapped_prose.py")
ctp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ctp)

# (name, source lines, rendered-text stub, must_flag)
CASES = [
    ("apx_a: sentence FRAGMENT after a terminal period (found 2026-07-26)", [
        "% elsewhere, restore the wider claim and say so; that is a fact only you can settle. It is organized as a registry-driven experimental framework rather than a",
        "collection of one-off scripts: name-keyed registries expose interchangeable",
    ], "released with the code. collection of one-off scripts: name-keyed registries", True),

    ("4_courb:187: half a PUBLISHED methodology sentence", [
        "% needed 468.2 pt; the reordered run-up puts the whole expression at about 227 pt. built by Delaunay triangulation over the geographic coordinates, with edges weighted by logarithmic decay of the Haversine distance and penalization for connections between distinct counties (GEOIDs).",
        "Over this graph, random walks are executed following the Node2Vec methodology.",
    ], "The POIs are organized into a spatial graph Over this graph, random walks are executed", True),

    ("5_mobiwac:385: four sentences incl. a required disclosure", [
        "% re-running preprocessing. Stated as five datasets, not six. The measurement bounds this channel rather than closing it, and three limits set how far it reaches: the probe is linear, it was run at Florida alone",
        "at one random initialization over five user-grouped folds, and it was run on those ancestor builds.",
    ], "the shipped encoder carries no future information about the visit being predicted.", True),

    ("2_fundamentals:366: SHORT tail, comma flush against the period", [
        "% the correction is to describe a cited system as its own authors describe it (AGENT_GUARDRAILS",
        "% citation protocol)., Nash-MTL treats",
        "the combination of task gradients as a bargaining game and takes the Nash solution as",
    ], "with convergence guarantees (51) the combination of task gradients as a bargaining game", True),

    ("6_conclusion:105: SHORT tail (7 words)", [
        "% out plain parameter count, which the trunk ablation does not bear on. a capacity-matched dedicated baseline, run after the",
        "Chapter manuscript was submitted and reported here as a frame-level analysis: a",
    ], "shared trunk as the source. Second, Chapter manuscript was submitted and reported", True),

    ("apx_b:188: SHORT tail (9 words)", [
        "% into the errata table.] The emphasis convention of the published category table, which",
        "bolds the better of the joint and single-task models per row and never bolds the HMRM",
    ], "audited and the other was not. bolds the better of the joint and single-task models", True),

    # --- negatives: things that MUST NOT be flagged -------------------------------------------
    ("negative: ordinary multi-line comment block", [
        "% [round4, REV-021] Mechanical re-typeset, not a content departure. The published sentence",
        "% (src_en/sections/metodology.tex:107) read \"The POI Encoder is trained independently\".",
        "The category embedding is generated by the POI Encoder, which is trained independently.",
    ], "The category embedding is generated by the POI Encoder, which is trained independently.", False),

    ("negative: self-contained ledger remark ending in a period", [
        "% Source: STATISTICAL_PROTOCOL.md:187-190. Claim unchanged. Revert if you prefer the duplication.",
        "The joint model outperforms the dedicated single-task category model at all six datasets.",
    ], "The joint model outperforms the dedicated single-task category model at all six datasets.", False),

    ("negative: comment whose tail names files and line numbers", [
        "% Verified three ways this session: (1) Navon et al., arXiv:2202.01017, Axiom 2.4 is affine",
        "% invariance; (2) tarik-new nash_mtl.py:99; (3) this repo's loss.py:105.",
        "Nash-MTL treats the combination of task gradients as a bargaining game.",
    ], "Nash-MTL treats the combination of task gradients as a bargaining game.", False),
]


def run() -> int:
    import re
    failures = []
    for name, lines, rendered, must_flag in CASES:
        pdf = re.sub(r"\s+", " ", rendered)
        tmp = HERE / "_fixture.tex"
        tmp.write_text("\n".join(lines) + "\n", encoding="utf8")
        try:
            hits = ctp.suspects_in(tmp, pdf)
        finally:
            tmp.unlink(missing_ok=True)
        flagged = bool(hits)
        ok = flagged == must_flag
        print(f"{'PASS' if ok else 'FAIL'}  {'flag' if must_flag else 'quiet':5s}  {name}")
        if not ok:
            failures.append(name)
            for h in hits:
                print(f"        unexpected hit: line {h[0]} tail={h[1][:70]!r}")
    print(f"\n{len(CASES) - len(failures)}/{len(CASES)} fixtures pass")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(run())
